# Usar una imagen base de Tomcat
FROM tomcat:9.0

# Copiar el archivo WAR al contenedor
COPY dist/ModuloCompras.war /usr/local/tomcat/webapps/

# Exponer el puerto en el que se ejecutará Tomcat
EXPOSE 8080